<section class="content">
	<div class="container-fluid">        	
		<div class="container">
			<div class="row app-one">
				<div class="col-sm-12">
                    <?php
                    if($this->dmat==0){
                        $carpeta = './uploads/usuarios/'.Session::get('id');
                        if (!file_exists($carpeta)) {
                            mkdir($carpeta, 0777, true);
                        }
                    }else{
                        $carpeta = './uploads/materias/'.$this->dmat;
                        if (!file_exists($carpeta)) {
                            mkdir($carpeta, 0777, true);
                        }
                    }
                    ?>

                    <div class="container-fluid adm-archivos">
                        <br>
                        <div class="row">
                            <div class="col-md-12">
        


                            <!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script> -->
                                <script type="text/javascript" src="<?=$_assets['js']?>jquery-2.2.2.min.js"></script>
                                <style type="text/css">
                                    .btn-file {
                                        position: relative;
                                        overflow: hidden;
                                    }
                                    .btn-file input[type=file] {
                                        position: absolute;
                                        top: 0;
                                        right: 0;
                                        min-width: 100%;
                                        min-height: 100%;
                                        font-size: 100px;
                                        text-align: right;
                                        filter: alpha(opacity=0);
                                        opacity: 0;
                                        outline: none;
                                        background: white;
                                        cursor: inherit;
                                        display: block;
                                    }
                                </style>
                                <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.js"></script>
                                <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
                                <script type="text/javascript">
                                    $(function() {

                                      // We can attach the `fileselect` event to all file inputs on the page
                                      $(document).on('change', ':file', function() {
                                        var input = $(this),
                                            numFiles = input.get(0).files ? input.get(0).files.length : 1,
                                            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                                        input.trigger('fileselect', [numFiles, label]);
                                      });

                                      // We can watch for our custom `fileselect` event like this
                                      $(document).ready( function() {
                                          $(':file').on('fileselect', function(event, numFiles, label) {

                                              var input = $(this).parents('.input-group').find(':text'),
                                                  log = numFiles > 1 ? numFiles + ' files selected' : label;

                                              if( input.length ) {
                                                  input.val(log);
                                              } else {
                                                  if( log ) alert(log);
                                              }

                                          });
                                      });
                                      
                                    });

                                    $(document).ready(function (){
                                       /* Valida el tamaño maximo de un archivo adjunto */
                                       $('.input-file').change(function (){
                                         var sizeByte = this.files[0].size;
                                         //var siezekiloByte = parseInt(sizeByte / 1024);
                                    	var siezekiloByte = parseFloat(sizeByte / 1024);
                                    	var siezeMB = parseFloat(siezekiloByte / 1024);
                                    	size = parseFloat($('#size').val()) + siezeMB
                                    	//alert(siezeMB+'-'+$('#size').val()+'-'+size);
                                         if(size >  500){
                                             alert('El tamaño supera el limite permitido');
                                             $(this).val('');
                                         }
                                       });
                                    });
                                    </script>
                                    <?php
                                    $sizekb = 0.0 ; $sizemb = 0.0 ; $cont = 0;
                                    if($this->dmat==0){
                                        $dir=opendir('./uploads/usuarios/'.Session::get('id'));
                                    }else{
                                        $dir=opendir('./uploads/materias/'.$this->dmat);
                                    }
                                    while ($file = readdir($dir)){ 
                                    if ($file != "." && $file != ".."){ 
                                    	if($this->dmat==0){
                                            $sizekb = (filesize('./uploads/usuarios/'.Session::get('id')."/".$file)/1024)/1024; $cont += $sizekb;
                                        }else{
                                            $sizekb = (filesize('./uploads/materias/'.$this->dmat."/".$file)/1024)/1024; $cont += $sizekb;
                                        }
                                    }}
                                    ?>
                                    <div class="panel-- panel-default">
                                        <div class="panel-heading text-center">
                                            <span><strong><span class="glyphicon glyphicon-hdd"></span> Manejo de archivos</strong></span>
                                        </div>
                                        <div class="panel-body">
                                            <form name="myForm" onsubmit="return validarImagen();" method="post" enctype="multipart/form-data" action="<?=BASE_URL.'drive/upload/'.Session::get('id').'/'.$this->dmat?>" class="form-datos1">
                                            <div class="col-md-12 subir-archivos">
                                               <div class="input-group">
                                               <?php if(Session::get('nivel')!=1 or $this->dmat==0){ ?>
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                            <div class="form-line focused">
                                                                <select class="form-control" name="tipo" id="tipo" onchange="document.location.href='<?=BASE_URL.'drive/index/'?>'+this.value">
                                                                    <option value="0">Espacio Personal...</option>
                                                                    <?php foreach ($this->materias as $mat) : ?>
                                                                        <option value="<?=$mat['mat_id']?>" <?php if($this->dmat==$mat['mat_id']){ ?>selected<?php } ?>><?=$mat['mat_desc']?></option>
                                                                    <?php endforeach; ?>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-6">
                                                            <div class="form-line">
                                                                <input type="text" class="form-control" readonly value="" placeholder="No se ha seleccionado ningún archivo..." required>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <label class="input-group-btn">
                                                        <span class="btn btn-default">
                                                            <span class="glyphicon glyphicon-folder-open"></span>&nbsp;Seleccionar archivo&nbsp;<input type="file" name="file" style="display: none;" class="input-file" required>
                                                        </span>
                                                    </label>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="col-md-6">
                                                            Espacio utilizado
                                                        </div>
                                                        <div class="col-md-6">
                                                            <?=$cont ?> MB
                                                        </div>                                
                                                    </div>
                                                    <div class="col-md-6">
                                                        <button class="btn btn-success btn-lg waves-effect btn-block" type="submit" >Subir archivo</button>
                                                    </div>
                                                </div>
                                                <?php }else{ ?>
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                            <div class="form-line focused">
                                                                <select class="form-control" name="tipo" id="tipo" onchange="document.location.href='<?=BASE_URL.'drive/index/'?>'+this.value">
                                                                    <option value="0">Espacio Personal...</option>
                                                                    <?php foreach ($this->materias as $mat) : ?>
                                                                        <option value="<?=$mat['mat_id']?>" <?php if($this->dmat==$mat['mat_id']){ ?>selected<?php } ?>><?=$mat['mat_desc']?></option>
                                                                    <?php endforeach; ?>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-6">
                                                            <div class="row">
                                                                <div class="col-md-12">
                                                                    <div class="col-md-6">
                                                                        Espacio utilizado
                                                                    </div>
                                                                    <div class="col-md-6">
                                                                        <?=$cont ?> MB
                                                                    </div>                                
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <?php } ?> 
                                                </div>                     
                                            </div>   
                                        </form>    
                                    </div>                
                                </div>                
                            </div>
                        </div>
    
    <div class="row">
        <div class="col-md-12">
            <div class="panel-- panel-default table-responsive">
                <div class="panel-heading text-center">
                    <span><strong><span class="glyphicon glyphicon-folder-open"> </span> Archivos</strong></span>
                </div>
                <table class="table table-bordered table-hover vmiddle tabla-datos" data-remove="<?=BASE_URL.'drive/remove/'.Session::get('id')?>">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nombre</th>
                            <th class="text-center">Acciones</th>
                            <th>Tamaño</th>
                            <th>Fecha</th>
                        </tr>
                    </thead>
                    <tbody>
						<?php
                        $sizekb = 0.0 ; $sizemb = 0.0 ; $cont = 0; $c = 1;
                        if($this->dmat==0){
                            $dir=opendir('./uploads/usuarios/'.Session::get('id'));
                        }else{
                            $dir=opendir('./uploads/materias/'.$this->dmat);
                        }
                        while ($file = readdir($dir)){ 
						if ($file != "." && $file != ".."){ 
                            date_default_timezone_set('America/La_Paz');
                            if($this->dmat==0){
        						$sizekb = (filesize('./uploads/usuarios/'.Session::get('id')."/".$file)/1024)/1024; $cont += $sizekb;
        						$datos = stat('./uploads/usuarios/'.Session::get('id')."/".$file); 
                            }else{
                                $sizekb = (filesize('./uploads/materias/'.$this->dmat."/".$file)/1024)/1024; $cont += $sizekb;
                                $datos = stat('./uploads/materias/'.$this->dmat."/".$file); 
                            }
    						$fecha = date ("d-m-Y H:i:s", $datos[10]);
                        ?>
                        <tr>
                            <td class="text-center"><?=$c ?></td>
                            <td><?=utf8_encode($file)?></td>
                            <td class="text-center">  
                                <?php
                                if($this->dmat==0){
                                    $url = BASE_URL.'drive/download/usuarios/'.Session::get('id').'/'.$file;
                                }else{
                                    $url = BASE_URL.'drive/download/materias/'.$this->dmat.'/'.$file;
                                }
                                ?>
                                <a href="<?=$url?>" title="descargar"><span class="btn btn-sm btn-warning glyphicon glyphicon-download"></span></a>
                                <?php if(Session::get('nivel')!=1 or $this->dmat==0){ ?>
                                <a href="#" title="Eliminar" class="borrar-item" data-item="<?=$file?>" data-id="<?=$file?>"><span class="btn btn-sm btn-danger glyphicon glyphicon-trash"></span></a>
                                <?php } ?>
                            </td>
                            <td><?=$sizekb?> MB</td>
                            <td><?=$fecha?></td>
                        </tr> 
                        <?php $c++; 
						}elseif($c==1){
						?>
                        <?php
						} }
						closedir($dir);
						?>
                        <input type="hidden" class="" id="size" name="size" value="<?=$cont?>">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
</div>
</div>

                    
				</div>
			</div>
		</div>
	</div>
</section>


